version: '3'

services:
  selenium:
    # selenium standalone-chrome으로도 작동하는 것 확인
    image: selenium/standalone-chrome
    shm_size: 512mb
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  cache_db:
    image: redis
    ports:
      - 6379:6379
  server:
    # image: rejs/github-sub:latest
    build: .
    ports:
      - 8080:80
    volumes:
      - .env:/code/.env # 설정 파일 적용법
      - .:/code

networks:
  default:
    driver: bridge
